package:
  name: "demon"
  version: "2.0.5"

source:
  git_rev: v2.0.5
  git_url: https://github.com/GiulioRossetti/DEMON

requirements:
  host:
    - python
    - setuptools
  build:
    - python
    - setuptools
  run:
    - python>=3.7
    - tqdm
    - networkx>=2.4

about:
  home: https://github.com/GiulioRossetti/DEMON
  license: BSD-2-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "DEMON - Overlapping Community Discovery"

extra:
  recipe-maintainers:
    - GiulioRossetti
